-- 1. Create Business Profiles Table
CREATE TABLE IF NOT EXISTS public.business_profiles (
  id uuid PRIMARY KEY DEFAULT auth.uid(),
  business_name text NOT NULL DEFAULT 'My Business',
  logo_url text,
  whatsapp_number text,
  upi_id text,
  invoice_footer text,
  currency text DEFAULT 'INR',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

ALTER TABLE public.business_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile"
  ON public.business_profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
  ON public.business_profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile"
  ON public.business_profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- 2. Create Inventory Table
CREATE TABLE IF NOT EXISTS public.inventory (
  id text PRIMARY KEY,
  name text NOT NULL,
  sku text,
  category text,
  quantity integer NOT NULL DEFAULT 0,
  unit text,
  price numeric NOT NULL DEFAULT 0,
  "lowStockThreshold" integer DEFAULT 10,
  "createdAt" timestamp with time zone DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read inventory" ON public.inventory FOR SELECT USING (true);
CREATE POLICY "Admin can write inventory" ON public.inventory FOR ALL USING (true);


-- 3. Create Customers Table
CREATE TABLE IF NOT EXISTS public.customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  phone text,
  name text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public access to customers" ON public.customers FOR ALL USING (true);


-- 4. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_phone text,
  raw_message text,
  items jsonb,
  language text,
  status text,
  total_amount numeric,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  is_voice bool
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public access to orders" ON public.orders FOR ALL USING (true);


-- 5. Create Invoices Table
CREATE TABLE IF NOT EXISTS public.invoices (
  id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id int4 REFERENCES public.orders(id) ON DELETE CASCADE,
  pdf_url text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public access to invoices" ON public.invoices FOR ALL USING (true);


-- 6. Create Storage Buckets
INSERT INTO storage.buckets (id, name, public) 
VALUES ('invoices', 'invoices', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access Invoices" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'invoices');

CREATE POLICY "Service Role Upload Invoices" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'invoices');

INSERT INTO storage.buckets (id, name, public) 
VALUES ('logos', 'logos', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Read Logos" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'logos');

CREATE POLICY "Auth Upload Logos" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'logos');
